// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package echopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import echopb_openstack_neutron "github.com/tangfeixiong/go-to-openstack-bootcamp/kopos/echopb/openstack/neutron"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OpenstackNeutronNetRequestData struct {
	Id      string                            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string                            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Router  *echopb_openstack_neutron.Router  `protobuf:"bytes,3,opt,name=router" json:"router,omitempty"`
	Network *echopb_openstack_neutron.Network `protobuf:"bytes,4,opt,name=network" json:"network,omitempty"`
}

func (m *OpenstackNeutronNetRequestData) Reset()                    { *m = OpenstackNeutronNetRequestData{} }
func (m *OpenstackNeutronNetRequestData) String() string            { return proto.CompactTextString(m) }
func (*OpenstackNeutronNetRequestData) ProtoMessage()               {}
func (*OpenstackNeutronNetRequestData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *OpenstackNeutronNetRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenstackNeutronNetRequestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpenstackNeutronNetRequestData) GetRouter() *echopb_openstack_neutron.Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *OpenstackNeutronNetRequestData) GetNetwork() *echopb_openstack_neutron.Network {
	if m != nil {
		return m.Network
	}
	return nil
}

type OpenstackNeutronNetResponseData struct {
	Id               string                                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             string                                  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Router           *echopb_openstack_neutron.Router        `protobuf:"bytes,3,opt,name=router" json:"router,omitempty"`
	Network          *echopb_openstack_neutron.Network       `protobuf:"bytes,4,opt,name=network" json:"network,omitempty"`
	InterfaceInfo    *echopb_openstack_neutron.InterfaceInfo `protobuf:"bytes,5,opt,name=interface_info,json=interfaceInfo" json:"interface_info,omitempty"`
	GatewayNetworkId string                                  `protobuf:"bytes,6,opt,name=gateway_network_id,json=gatewayNetworkId" json:"gateway_network_id,omitempty"`
}

func (m *OpenstackNeutronNetResponseData) Reset()                    { *m = OpenstackNeutronNetResponseData{} }
func (m *OpenstackNeutronNetResponseData) String() string            { return proto.CompactTextString(m) }
func (*OpenstackNeutronNetResponseData) ProtoMessage()               {}
func (*OpenstackNeutronNetResponseData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *OpenstackNeutronNetResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenstackNeutronNetResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpenstackNeutronNetResponseData) GetRouter() *echopb_openstack_neutron.Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *OpenstackNeutronNetResponseData) GetNetwork() *echopb_openstack_neutron.Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *OpenstackNeutronNetResponseData) GetInterfaceInfo() *echopb_openstack_neutron.InterfaceInfo {
	if m != nil {
		return m.InterfaceInfo
	}
	return nil
}

func (m *OpenstackNeutronNetResponseData) GetGatewayNetworkId() string {
	if m != nil {
		return m.GatewayNetworkId
	}
	return ""
}

type ConsoleResourceRequestData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ConsoleResourceRequestData) Reset()                    { *m = ConsoleResourceRequestData{} }
func (m *ConsoleResourceRequestData) String() string            { return proto.CompactTextString(m) }
func (*ConsoleResourceRequestData) ProtoMessage()               {}
func (*ConsoleResourceRequestData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ConsoleResourceRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConsoleResourceRequestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConsoleResourceResponseData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ConsoleResourceResponseData) Reset()                    { *m = ConsoleResourceResponseData{} }
func (m *ConsoleResourceResponseData) String() string            { return proto.CompactTextString(m) }
func (*ConsoleResourceResponseData) ProtoMessage()               {}
func (*ConsoleResourceResponseData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ConsoleResourceResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConsoleResourceResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TraineeDroneRequestData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *TraineeDroneRequestData) Reset()                    { *m = TraineeDroneRequestData{} }
func (m *TraineeDroneRequestData) String() string            { return proto.CompactTextString(m) }
func (*TraineeDroneRequestData) ProtoMessage()               {}
func (*TraineeDroneRequestData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *TraineeDroneRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TraineeDroneRequestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TraineeDroneResponseData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *TraineeDroneResponseData) Reset()                    { *m = TraineeDroneResponseData{} }
func (m *TraineeDroneResponseData) String() string            { return proto.CompactTextString(m) }
func (*TraineeDroneResponseData) ProtoMessage()               {}
func (*TraineeDroneResponseData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *TraineeDroneResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TraineeDroneResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DefensiveDroneRequestData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DefensiveDroneRequestData) Reset()                    { *m = DefensiveDroneRequestData{} }
func (m *DefensiveDroneRequestData) String() string            { return proto.CompactTextString(m) }
func (*DefensiveDroneRequestData) ProtoMessage()               {}
func (*DefensiveDroneRequestData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DefensiveDroneRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DefensiveDroneRequestData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DefensiveDroneResponseData struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DefensiveDroneResponseData) Reset()                    { *m = DefensiveDroneResponseData{} }
func (m *DefensiveDroneResponseData) String() string            { return proto.CompactTextString(m) }
func (*DefensiveDroneResponseData) ProtoMessage()               {}
func (*DefensiveDroneResponseData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DefensiveDroneResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DefensiveDroneResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenstackNeutronNetRequestData)(nil), "echopb.OpenstackNeutronNetRequestData")
	proto.RegisterType((*OpenstackNeutronNetResponseData)(nil), "echopb.OpenstackNeutronNetResponseData")
	proto.RegisterType((*ConsoleResourceRequestData)(nil), "echopb.ConsoleResourceRequestData")
	proto.RegisterType((*ConsoleResourceResponseData)(nil), "echopb.ConsoleResourceResponseData")
	proto.RegisterType((*TraineeDroneRequestData)(nil), "echopb.TraineeDroneRequestData")
	proto.RegisterType((*TraineeDroneResponseData)(nil), "echopb.TraineeDroneResponseData")
	proto.RegisterType((*DefensiveDroneRequestData)(nil), "echopb.DefensiveDroneRequestData")
	proto.RegisterType((*DefensiveDroneResponseData)(nil), "echopb.DefensiveDroneResponseData")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcb, 0x4f, 0xdb, 0x30,
	0x18, 0x57, 0xb2, 0x2e, 0xd3, 0xbe, 0x69, 0xd5, 0xe4, 0xcb, 0xb2, 0x4e, 0xda, 0x4a, 0x2e, 0xf4,
	0x40, 0x13, 0x09, 0x2e, 0x48, 0x08, 0x28, 0xa2, 0x97, 0x5e, 0x82, 0x14, 0x71, 0x45, 0x95, 0x93,
	0x7c, 0x49, 0xad, 0x52, 0x7f, 0xc1, 0x76, 0x28, 0xfc, 0x6b, 0xf0, 0xcf, 0x21, 0xe5, 0x51, 0xf1,
	0xea, 0x21, 0x9c, 0x38, 0xf9, 0xf1, 0x7b, 0xda, 0x96, 0x01, 0x52, 0x6e, 0xb8, 0x5f, 0x28, 0x32,
	0xc4, 0x1c, 0x4c, 0x16, 0x54, 0xc4, 0x83, 0xab, 0x5c, 0x98, 0x45, 0x19, 0xfb, 0x09, 0xad, 0x02,
	0xc3, 0x65, 0x9e, 0xa1, 0xb8, 0x13, 0x24, 0xf3, 0x20, 0xa7, 0xb1, 0xa1, 0x31, 0x15, 0x28, 0xb5,
	0xe1, 0xc9, 0x72, 0x1c, 0x13, 0x99, 0x84, 0xaf, 0x8a, 0x60, 0x49, 0x05, 0xe9, 0xa0, 0x96, 0x07,
	0x1b, 0x3c, 0x90, 0x58, 0x1a, 0x45, 0xb2, 0x1d, 0xeb, 0x18, 0xef, 0xd1, 0x82, 0x7f, 0x17, 0x2d,
	0x27, 0xac, 0xa1, 0x10, 0x4d, 0x84, 0x37, 0x25, 0x6a, 0x33, 0xe5, 0x86, 0xb3, 0x3e, 0xd8, 0x22,
	0x75, 0xad, 0xa1, 0x35, 0xfa, 0x1e, 0xd9, 0x22, 0x65, 0x0c, 0x7a, 0x92, 0xaf, 0xd0, 0xb5, 0xab,
	0x9d, 0x6a, 0xce, 0x0e, 0xc1, 0x51, 0x54, 0x1a, 0x54, 0xee, 0x97, 0xa1, 0x35, 0xfa, 0xb1, 0x3f,
	0xf4, 0xeb, 0x7c, 0x7f, 0x93, 0xef, 0xb7, 0xb9, 0x51, 0xc5, 0x8b, 0x1a, 0x3e, 0x3b, 0x82, 0x6f,
	0x12, 0xcd, 0x9a, 0xd4, 0xd2, 0xed, 0x55, 0xd2, 0x9d, 0xed, 0xd2, 0xb0, 0x26, 0x46, 0xad, 0xc2,
	0x7b, 0xb0, 0xe1, 0xff, 0xbb, 0xed, 0x75, 0x41, 0x52, 0xe3, 0x27, 0xaf, 0xcf, 0x42, 0xe8, 0x0b,
	0x69, 0x50, 0x65, 0x3c, 0xc1, 0xb9, 0x90, 0x19, 0xb9, 0x5f, 0x2b, 0x8f, 0xdd, 0xed, 0x1e, 0xb3,
	0x96, 0x3f, 0x93, 0x19, 0x45, 0x3f, 0xc5, 0xf3, 0x25, 0xdb, 0x03, 0x96, 0x73, 0x83, 0x6b, 0x7e,
	0x3f, 0x6f, 0x22, 0xe6, 0x22, 0x75, 0x9d, 0xea, 0xa0, 0xbf, 0x1a, 0xa4, 0x29, 0x31, 0x4b, 0xbd,
	0x09, 0x0c, 0xce, 0x49, 0x6a, 0xba, 0xc6, 0x08, 0x35, 0x95, 0x2a, 0xc1, 0x8e, 0xaf, 0xee, 0x9d,
	0xc1, 0xdf, 0x37, 0x0e, 0xdd, 0x6e, 0xde, 0x3b, 0x86, 0xdf, 0x97, 0x8a, 0x0b, 0x89, 0x38, 0x55,
	0x24, 0x3b, 0x37, 0x38, 0x01, 0xf7, 0xa5, 0xbc, 0x63, 0xfc, 0x29, 0xfc, 0x99, 0x62, 0x86, 0x52,
	0x8b, 0xdb, 0x8f, 0x15, 0x98, 0xc0, 0xe0, 0xb5, 0x41, 0xb7, 0x0a, 0xb1, 0x53, 0x7d, 0xc4, 0x83,
	0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x21, 0x10, 0x3d, 0xfd, 0x03, 0x00, 0x00,
}
